// Generated by tools/import-bundle.js — do not edit by hand.
const CACHE = 'im-suite-5a5dc39c1851';
const PRECACHE = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "img/a9dc5f43.png",
  "vendor/lucide.js",
  "fonts/bc56c6fb.woff2",
  "fonts/d8696bac.woff2",
  "fonts/260837bf.woff2",
  "fonts/9bcb884f.woff2",
  "fonts/d8030af5.woff2",
  "fonts/1296db44.woff2",
  "fonts/0d0284cd.woff2",
  "fonts/e7b148e4.woff2",
  "fonts/34faa1ab.woff2",
  "fonts/eab99d01.woff2",
  "fonts/c4e549a7.woff2",
  "fonts/2ba6f27e.woff2",
  "fonts/a2086467.woff2",
  "fonts/9ad8d99f.woff2",
  "fonts/6d03c81a.woff2",
  "fonts/75875dd3.woff2",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('im-suite-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // optional online extras (fonts, time check) go straight to network
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
      return res;
    }).catch(() => req.mode === 'navigate' ? caches.match('./index.html') : Response.error()))
  );
});
